# Generated by Django 3.1.4 on 2020-12-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
